# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K9salpha < Formula
  desc "Kubernetes CLI To Manage Your Clusters In Style!"
  homepage "https://k9salpha.io/"
  version "1.0.0-rc.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/imhotepio/k9salpha/releases/download/v1.0.0-rc.0/k9salpha_Darwin_x86_64.tar.gz"
    sha256 "5b3f299e1eb7e5a7e0368d0f1bbe8460727a7c957c6b1fbd91b074db8165c1e6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/imhotepio/k9salpha/releases/download/v1.0.0-rc.0/k9salpha_Linux_x86_64.tar.gz"
    sha256 "35feadedd3f7517daaac0747cbbc5d41ce5edde12145722c18b4a59d8dbb78e5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/imhotepio/k9salpha/releases/download/v1.0.0-rc.0/k9salpha_Linux_arm64.tar.gz"
    sha256 "4d323e11065bc3cf8577d9c69ecd4c51520963788b9453f31ee7437560e4be19"
  end

  def install
    bin.install "k9salpha"
  end

  test do
    system "k9salpha version"
  end
end
